export const productsDB = {
  1: { id: 1, name: 'Wireless Noise-Cancelling Headphones', price: 299.99, rating: 4.8, reviews: 120, vendor: 'AudioTech Store', stock: 15, category: 'Electronics', description: 'Experience pure audio bliss with our industry-leading noise cancellation technology. Features 30-hour battery life and supreme comfort.', image: 'https://m.media-amazon.com/images/I/714eIaCy37L.jpg', sizes: [] },
  2: { id: 2, name: 'Minimalist Smartwatch', price: 199.50, rating: 4.6, reviews: 85, vendor: 'TimePiece Co.', stock: 8, category: 'Electronics', description: 'Stay connected and track your fitness with this sleek minimalist smartwatch. Compatible with all major smartphones.', image: 'https://tse3.mm.bing.net/th/id/OIP.qlhHlQgPpgZcNJAmoMH_YQHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3', sizes: [] },
  3: { id: 3, name: 'Water Bottle', price: 24.00, rating: 4.9, reviews: 320, vendor: 'GreenLife', stock: 150, category: 'Home & Living', description: 'Keeps your drinks cold for 24 hours or hot for 12 hours. Made from recycled materials.', image: 'https://tse2.mm.bing.net/th/id/OIP.Tf5HDUjfXDa9AvLCy6JgXAHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3', sizes: [] },
  4: { id: 4, name: 'Leather Wallet', price: 59.99, rating: 4.7, reviews: 42, vendor: 'LeatherCraft', stock: 5, category: 'Fashion', description: 'Handcrafted genuine leather wallet with RFID blocking technology.', image: 'https://i.etsystatic.com/16971055/r/il/4e0cf5/3021061575/il_1588xN.3021061575_7om9.jpg', sizes: [] },
  5: { id: 5, name: 'Cotton T-Shirt', price: 19.99, rating: 4.5, reviews: 210, vendor: 'Apparel Basics', stock: 50, category: 'Fashion', description: '100% organic cotton t-shirt. Breathable, comfortable, and perfect for everyday wear.', image: 'https://th.bing.com/th/id/OIP.BtLR-_NzqyKCsmAH5Js3cgHaHa?w=202&h=202&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3', sizes: ['S', 'M', 'L', 'XL'] },
  6: { id: 6, name: 'Camera Lens', price: 899.99, rating: 4.9, reviews: 32, vendor: 'PhotoGear', stock: 3, category: 'Electronics', description: 'Capture stunning photos with this 50mm f/1.4 prime lens. Perfect for portraits and low-light photography.', image: 'https://petapixel.com/assets/uploads/2023/01/camera-lenses-with-a-lens-cap.jpg', sizes: [] },
  7: { id: 7, name: 'Running Shoes', price: 129.99, rating: 4.4, reviews: 145, vendor: 'Direct', stock: 24, category: 'Fashion', description: 'Lightweight and breathable running shoes with excellent cushioning.', image: 'https://m.media-amazon.com/images/I/81oZvHubPcL._AC_UL480_FMwebp_QL65_.jpg', sizes: ['8', '9', '10', '11', '12'] },
  8: { id: 8, name: 'Coffee Mug', price: 14.50, rating: 4.8, reviews: 92, vendor: 'HomeGoods', stock: 60, category: 'Home & Living', description: 'Handmade ceramic mug. Microwave and dishwasher safe.', image: 'https://m.media-amazon.com/images/I/51Mlh71sMEL._AC_UL480_FMwebp_QL65_.jpg', sizes: [] },
  9: { id: 9, name: 'Matte Lipstick', price: 300, rating: 4.5, reviews: 89, vendor: 'Swiss Beauty', stock: 50, category: 'Beauty', description: 'Velvety Matte Finish- The Swiss Beauty Select Dare To Matte Lipstick boasts a bold matte finish that looks incredibly rich.', image: 'https://m.media-amazon.com/images/I/61Nx1bvauiL._SX679_.jpg', sizes: []},
 10: { id:10, name: 'Mascara', price: 214, rating: 4.6, reviews: 90, vendor: 'MARS', stock: 50, category: 'Beauty', description: 'MARS Fabulash Mascara is made with naturally moisturising beeswax to nourish lashes.', image: 'https://m.media-amazon.com/images/I/61Ys8pmoRWL._SX679_.jpg', sizes: []},
 11: { id: 11, name: 'Shinchan Crawling Toy', price: 150, rating: 4.7, reviews: 59, vendor: 'SIMPLIFY', stock: 60, category: 'Toys', description: 'Iconic Shin Chan Pose: Features a crawling action just like the character.', image: 'https://m.media-amazon.com/images/I/51K+UrYDy9L._SX679_.jpg', sizes: []},
 12: { id: 12, name: 'Rolls-Royce Spectre', price: 300, rating: 4.6, reviews: 70, vendor: 'Advisian', stock: 60, category: 'Toys', description: 'Made of high-quality materials, these cars are durable, safe, non-toxic and lead-free toys. Can be moved..', image: 'https://m.media-amazon.com/images/I/51p2PRZY4VL._SX679_.jpg', sizes: []},
 13:{id: 13, name:'Tata Salt',price:28,rating:4.7,reviews:80,vendor:'TATA',stock:78,category:'Groceries',description:'Untouched by hand, Tata Salt offers an assurance of Iodine. With vacuum evaporation technology, Tata namak offers a hygienic alternative to your regular table salt.',image:'https://m.media-amazon.com/images/I/614mm2hYHyL._SX679_.jpg',sizes:[]},
 14:{id:14,name:'Car Scratch Remover',price:300,rating:4.5,reviews:85,vendor:'Auto',stock:56,category:'Automotive',description:' The special-purpose black car paint is a universal colour that can blend with most car shades.',image:'https://m.media-amazon.com/images/I/61sxvCKbkBL._SX679_.jpg',sizes:[]},
 15:{id:15,name:'Skipping Rope',price:200,rating:4.8,reviews:89,vendor:'Redify',stock:45,category:'Sports',description:'Our skipping ropes are designed to be 9 ft long, allowing you to effortlessly customize the length to perfectly suit your height. Simply trim the excess rope as needed.',image:'https://m.media-amazon.com/images/I/71unDV7tXIL._SX679_.jpg',sizes:[]}
};

export const servicesDB = [
  { id: 1, name: 'AC Repair & Servicing', price: 49, rating: 4.8, reviews: 124, image: 'https://briggsclimatecontrol.co.uk/wp-content/uploads/2023/01/air-con-servicing.jpg', vendor: 'Home Services', category: 'Services' },
  { id: 2, name: 'Home Cleaning', price: 79, rating: 4.9, reviews: 342, image: 'https://freshysites.com/wp-content/uploads/house-cleaning.jpg', vendor: 'Home Services', category: 'Services' },
  { id: 3, name: 'Plumbing Services', price: 59, rating: 4.7, reviews: 89, image: 'https://as2.ftcdn.net/v2/jpg/02/20/20/41/1000_F_220204174_vfgB0Vo2i4MZ8Sv5hmtsx5IwcvrDCZox.jpg', vendor: 'Home Services', category: 'Services' },
  { id: 4, name: 'Appliance Repair', price: 69, rating: 4.6, reviews: 156, image: 'https://wilshirerefrigeration.com/wp-content/uploads/2020/05/Service-technician-refrigerator-appliance-repair.jpg', vendor: 'Home Services', category: 'Services' },
];

